[2022-12-16 13:03:06,579] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 13:03:46,511] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 13:03:46,511] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 13:03:46,511] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 13:09:47,781] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [1.63, 127.0.0.1:50179]
[2022-12-16 13:09:50,705] [log.py:241] [log:log_response] [WARNING]- Not Found: /
[2022-12-16 13:09:50,707] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET / 404 [2.30, 127.0.0.1:50185]
[2022-12-16 13:09:53,477] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [7.25, 127.0.0.1:50181]
[2022-12-16 13:09:54,212] [log.py:241] [log:log_response] [WARNING]- Not Found: /jquery.min.js
[2022-12-16 13:09:54,213] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /jquery.min.js 404 [0.02, 127.0.0.1:50192]
[2022-12-16 13:09:54,378] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-12-16 13:09:54,379] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /favicon.ico 404 [0.03, 127.0.0.1:50192]
[2022-12-16 13:09:58,541] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.40, 127.0.0.1:50194]
[2022-12-16 13:09:59,156] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css 304 [0.24, 127.0.0.1:50194]
[2022-12-16 13:09:59,160] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap-tweaks.css 304 [0.16, 127.0.0.1:50195]
[2022-12-16 13:09:59,225] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/prettify.css 304 [0.16, 127.0.0.1:50199]
[2022-12-16 13:09:59,228] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/default.css 304 [0.14, 127.0.0.1:50200]
[2022-12-16 13:09:59,389] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/jquery-3.5.1.min.js 304 [0.28, 127.0.0.1:50201]
[2022-12-16 13:09:59,393] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/ajax-form.js 304 [0.27, 127.0.0.1:50202]
[2022-12-16 13:09:59,397] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/csrf.js 304 [0.16, 127.0.0.1:50194]
[2022-12-16 13:09:59,401] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/default.js 304 [0.17, 127.0.0.1:50200]
[2022-12-16 13:09:59,406] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/bootstrap.min.js 304 [0.17, 127.0.0.1:50195]
[2022-12-16 13:09:59,409] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/prettify-min.js 304 [0.17, 127.0.0.1:50199]
[2022-12-16 13:09:59,606] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/img/grid.png 304 [0.04, 127.0.0.1:50199]
[2022-12-16 13:10:00,132] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 304 [0.04, 127.0.0.1:50199]
[2022-12-16 13:10:01,324] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 13:10:01,326] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:50199]
[2022-12-16 13:15:26,226] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [1.50, 127.0.0.1:50326]
[2022-12-16 13:15:26,510] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.78, 127.0.0.1:50325]
[2022-12-16 13:20:12,817] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:50519]
[2022-12-16 13:20:13,215] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.27, 127.0.0.1:50527]
[2022-12-16 13:24:42,360] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.19, 127.0.0.1:50790]
[2022-12-16 13:24:42,619] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:50793]
[2022-12-16 13:26:41,419] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.49, 127.0.0.1:50964]
[2022-12-16 13:26:41,448] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.52, 127.0.0.1:50965]
[2022-12-16 13:27:58,930] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:51046]
[2022-12-16 13:27:59,058] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:51049]
[2022-12-16 13:29:36,608] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:51175]
[2022-12-16 13:29:36,811] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:51178]
[2022-12-16 13:31:46,355] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.22, 127.0.0.1:51429]
[2022-12-16 13:31:46,575] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:51432]
[2022-12-16 13:32:05,314] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:51472]
[2022-12-16 13:32:05,540] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:51475]
[2022-12-16 13:33:19,163] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [1.53, 127.0.0.1:51577]
[2022-12-16 13:33:20,906] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [2.95, 127.0.0.1:51579]
[2022-12-16 13:34:03,263] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.69, 127.0.0.1:51667]
[2022-12-16 13:34:03,561] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.94, 127.0.0.1:51670]
[2022-12-16 13:36:03,855] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.35, 127.0.0.1:51903]
[2022-12-16 13:36:03,947] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.29, 127.0.0.1:51907]
[2022-12-16 13:39:29,007] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:52227]
[2022-12-16 13:39:29,529] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.38, 127.0.0.1:52230]
[2022-12-16 13:39:29,636] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:52233]
[2022-12-16 13:39:30,228] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.38, 127.0.0.1:52240]
[2022-12-16 13:39:30,312] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:52243]
[2022-12-16 13:39:30,830] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:52247]
[2022-12-16 13:40:00,733] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:52290]
[2022-12-16 13:40:01,130] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:52293]
[2022-12-16 13:40:42,337] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:52351]
[2022-12-16 13:40:42,747] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:52354]
[2022-12-16 13:41:19,368] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:52408]
[2022-12-16 13:41:19,704] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:52413]
[2022-12-16 13:42:36,100] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:52511]
[2022-12-16 13:42:36,399] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:52514]
[2022-12-16 13:43:05,377] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:52551]
[2022-12-16 13:43:05,756] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:52554]
[2022-12-16 13:43:26,278] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:52588]
[2022-12-16 13:43:26,630] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:52591]
[2022-12-16 13:48:10,532] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.24, 127.0.0.1:52952]
[2022-12-16 13:48:10,730] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:52955]
[2022-12-16 13:49:03,148] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:53026]
[2022-12-16 13:49:03,496] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:53030]
[2022-12-16 13:49:23,438] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.98, 127.0.0.1:53062]
[2022-12-16 13:49:24,655] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=38 200 [0.11, 127.0.0.1:53068]
[2022-12-16 13:49:27,694] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=37 200 [0.10, 127.0.0.1:53077]
[2022-12-16 13:49:30,105] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.03, 127.0.0.1:53082]
[2022-12-16 13:57:32,024] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 13:57:35,904] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 13:57:35,904] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 13:57:35,904] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 13:59:10,413] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\models.py changed, reloading.
[2022-12-16 13:59:13,546] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 13:59:14,001] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 13:59:14,001] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 13:59:14,001] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:00:26,902] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.48, 127.0.0.1:53893]
[2022-12-16 14:00:27,029] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.60, 127.0.0.1:53894]
[2022-12-16 14:02:18,335] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 14:02:19,043] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 14:02:19,043] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 14:02:19,043] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:02:35,948] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.30, 127.0.0.1:54080]
[2022-12-16 14:02:44,861] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.11, 127.0.0.1:54092]
[2022-12-16 14:03:23,188] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 14:03:23,625] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 14:03:23,625] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 14:03:23,625] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:03:38,986] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.00, 127.0.0.1:54125]
[2022-12-16 14:03:45,530] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:03:45,532] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.47, 127.0.0.1:54132]
[2022-12-16 14:08:03,275] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:54231]
[2022-12-16 14:08:34,922] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.36, 127.0.0.1:54256]
[2022-12-16 14:10:09,451] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:54337]
[2022-12-16 14:11:43,912] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.35, 127.0.0.1:54457]
[2022-12-16 14:11:47,085] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.98, 127.0.0.1:54471]
[2022-12-16 14:13:42,726] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:54612]
[2022-12-16 14:13:48,482] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.16, 127.0.0.1:54623]
[2022-12-16 14:14:30,710] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:54677]
[2022-12-16 14:14:47,013] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:54704]
[2022-12-16 14:14:51,556] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.19, 127.0.0.1:54715]
[2022-12-16 14:14:51,562] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:54716]
[2022-12-16 14:15:00,193] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.15, 127.0.0.1:54727]
[2022-12-16 14:16:26,427] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.27, 127.0.0.1:54765]
[2022-12-16 14:16:26,751] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:16:26,752] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.07, 127.0.0.1:54765]
[2022-12-16 14:16:45,864] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.14, 127.0.0.1:54775]
[2022-12-16 14:16:46,474] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:16:46,475] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:54775]
[2022-12-16 14:18:11,525] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:54874]
[2022-12-16 14:18:11,654] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:54877]
[2022-12-16 14:18:19,649] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=38 200 [0.07, 127.0.0.1:54897]
[2022-12-16 14:18:57,966] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.06, 127.0.0.1:54949]
[2022-12-16 14:19:07,442] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.16, 127.0.0.1:54961]
[2022-12-16 14:19:07,626] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:19:07,629] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:54961]
[2022-12-16 14:19:17,249] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.06, 127.0.0.1:54979]
[2022-12-16 14:30:02,437] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.81, 127.0.0.1:56379]
[2022-12-16 14:30:02,639] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.12, 127.0.0.1:56376]
[2022-12-16 14:30:11,935] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.03, 127.0.0.1:56402]
[2022-12-16 14:30:46,865] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 428, in post
    relateds=datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-16 14:30:47,605] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /cases/ 500 [3.84, 127.0.0.1:56450]
[2022-12-16 14:31:58,896] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 428, in post
    relateds=datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-16 14:31:58,907] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /cases/ 500 [0.56, 127.0.0.1:56559]
[2022-12-16 14:32:51,755] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:32:51,756] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.18, 127.0.0.1:56624]
[2022-12-16 14:34:08,899] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.17, 127.0.0.1:56724]
[2022-12-16 14:34:09,079] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:34:09,081] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:56724]
[2022-12-16 14:34:32,850] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/?page=2 200 [1.21, 127.0.0.1:56755]
[2022-12-16 14:34:39,814] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.19, 127.0.0.1:56766]
[2022-12-16 14:34:40,030] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:34:40,032] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.06, 127.0.0.1:56766]
[2022-12-16 14:35:59,274] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:56878]
[2022-12-16 14:35:59,566] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:56881]
[2022-12-16 14:36:06,712] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.07, 127.0.0.1:56894]
[2022-12-16 14:36:19,280] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.13, 127.0.0.1:56914]
[2022-12-16 14:36:57,111] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 428, in post
    relateds=datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-16 14:36:57,131] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /cases/?page=2 500 [0.24, 127.0.0.1:56961]
[2022-12-16 14:36:57,456] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:36:57,458] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:56961]
[2022-12-16 14:37:01,468] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.20, 127.0.0.1:56961]
[2022-12-16 14:37:13,580] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css.map 200 [1.12, 127.0.0.1:56987]
[2022-12-16 14:37:19,609] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 428, in post
    relateds=datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-16 14:37:19,617] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /cases/?page=2 500 [0.24, 127.0.0.1:56995]
[2022-12-16 14:37:19,884] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:37:19,886] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:56995]
[2022-12-16 14:37:36,348] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css.map 200 [0.02, 127.0.0.1:57018]
[2022-12-16 14:37:42,430] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 428, in post
    relateds=datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-16 14:37:42,440] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /cases/?page=2 500 [0.20, 127.0.0.1:57028]
[2022-12-16 14:37:42,781] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:37:42,784] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:57028]
[2022-12-16 14:39:58,171] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 14:40:03,872] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 14:40:03,872] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 14:40:03,872] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:40:07,976] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css.map 200 [0.20, 127.0.0.1:57219]
[2022-12-16 14:40:16,572] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.94, 127.0.0.1:57231]
[2022-12-16 14:40:16,847] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css.map 200 [0.02, 127.0.0.1:57231]
[2022-12-16 14:40:17,350] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:40:17,352] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.26, 127.0.0.1:57231]
[2022-12-16 14:40:27,427] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 428, in post
    relateds=datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-16 14:40:27,438] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /cases/?page=2 500 [0.36, 127.0.0.1:57247]
[2022-12-16 14:40:27,763] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:40:27,765] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.06, 127.0.0.1:57247]
[2022-12-16 14:40:39,089] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css.map 200 [0.02, 127.0.0.1:57267]
[2022-12-16 14:40:44,462] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'related'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 428, in post
    relateds=datas['related']
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'related'
[2022-12-16 14:40:44,471] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /cases/?page=2 500 [0.15, 127.0.0.1:57277]
[2022-12-16 14:40:44,804] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 14:40:44,806] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:57277]
[2022-12-16 14:40:58,030] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.08, 127.0.0.1:57299]
[2022-12-16 14:42:32,725] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:57423]
[2022-12-16 14:42:32,810] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:57426]
[2022-12-16 14:42:42,356] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=38 200 [0.09, 127.0.0.1:57442]
[2022-12-16 14:43:05,316] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.14, 127.0.0.1:57478]
[2022-12-16 14:44:50,902] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\models.py changed, reloading.
[2022-12-16 14:44:54,082] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 14:44:54,573] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 14:44:54,574] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 14:44:54,576] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:48:54,087] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:57911]
[2022-12-16 14:48:54,353] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:57914]
[2022-12-16 14:49:03,515] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 14:49:03,921] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 14:49:03,921] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 14:49:03,921] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:49:35,978] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [1.02, 127.0.0.1:57988]
[2022-12-16 14:49:36,131] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.15, 127.0.0.1:57989]
[2022-12-16 14:49:42,290] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=38 200 [0.05, 127.0.0.1:58012]
[2022-12-16 14:49:59,091] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.29, 127.0.0.1:58036]
[2022-12-16 14:52:00,530] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 14:52:01,170] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 14:52:01,170] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 14:52:01,186] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:52:05,696] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.19, 127.0.0.1:58223]
[2022-12-16 14:53:24,829] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 14:53:25,344] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 14:53:25,360] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 14:53:25,360] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:54:02,330] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:58380]
[2022-12-16 14:54:02,512] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:58383]
[2022-12-16 14:54:35,814] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:58429]
[2022-12-16 14:54:36,173] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:58433]
[2022-12-16 14:54:40,675] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\models.py changed, reloading.
[2022-12-16 14:54:55,111] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 14:54:57,250] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 14:54:57,250] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 14:54:57,250] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 14:55:49,888] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:58535]
[2022-12-16 14:55:50,146] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:58539]
[2022-12-16 14:56:09,231] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=38 200 [0.07, 127.0.0.1:58566]
[2022-12-16 14:56:29,203] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.16, 127.0.0.1:58597]
[2022-12-16 14:57:20,028] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:58669]
[2022-12-16 14:57:20,480] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.36, 127.0.0.1:58672]
[2022-12-16 14:57:26,683] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.08, 127.0.0.1:58685]
[2022-12-16 14:57:37,990] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.19, 127.0.0.1:58702]
[2022-12-16 15:00:39,557] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.63, 127.0.0.1:58930]
[2022-12-16 15:00:39,793] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.91, 127.0.0.1:58928]
[2022-12-16 15:00:43,784] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=38 200 [0.25, 127.0.0.1:58938]
[2022-12-16 15:00:47,982] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=37 200 [0.10, 127.0.0.1:58948]
[2022-12-16 15:01:00,011] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.05, 127.0.0.1:58968]
[2022-12-16 15:01:22,387] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:59005]
[2022-12-16 15:01:25,344] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.08, 127.0.0.1:59015]
[2022-12-16 15:03:15,922] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:59075]
[2022-12-16 15:04:14,849] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:59107]
[2022-12-16 15:04:22,619] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [1.09, 127.0.0.1:59111]
[2022-12-16 15:04:24,275] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:04:24,277] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.25, 127.0.0.1:59111]
[2022-12-16 15:04:37,481] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:59126]
[2022-12-16 15:04:48,702] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:59140]
[2022-12-16 15:04:53,251] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.09, 127.0.0.1:59148]
[2022-12-16 15:05:04,016] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.09, 127.0.0.1:59156]
[2022-12-16 15:05:04,331] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:05:04,332] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:59156]
[2022-12-16 15:05:13,179] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:59162]
[2022-12-16 15:05:13,483] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:05:13,485] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:59162]
[2022-12-16 15:06:47,797] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:59201]
[2022-12-16 15:06:53,695] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.15, 127.0.0.1:59209]
[2022-12-16 15:07:17,336] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.34, 127.0.0.1:59237]
[2022-12-16 15:08:20,665] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:59329]
[2022-12-16 15:08:30,289] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.32, 127.0.0.1:59353]
[2022-12-16 15:16:58,441] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [2.58, 127.0.0.1:60110]
[2022-12-16 15:17:54,344] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:60182]
[2022-12-16 15:18:14,475] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:60205]
[2022-12-16 15:18:19,342] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.06, 127.0.0.1:60212]
[2022-12-16 15:18:22,679] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.09, 127.0.0.1:60217]
[2022-12-16 15:18:26,755] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=1 200 [0.12, 127.0.0.1:60224]
[2022-12-16 15:19:05,615] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:60248]
[2022-12-16 15:20:20,842] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:60288]
[2022-12-16 15:21:40,184] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-16 15:23:03,058] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 15:23:14,167] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 15:23:14,229] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 15:23:14,229] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 15:24:09,750] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 457, in get
    for case in serializer.data:
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 686, in to_representation
    return [
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py", line 49, in get_is_online_response
    return obj.get_is_online_display()
AttributeError: 'casenew' object has no attribute 'get_is_online_display'
[2022-12-16 15:24:09,764] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [5.88, 127.0.0.1:60438]
[2022-12-16 15:24:11,470] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:24:11,472] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.11, 127.0.0.1:60438]
[2022-12-16 15:24:54,913] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-16 15:29:26,393] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 15:29:29,805] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 15:29:29,821] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 15:29:29,821] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 15:38:47,899] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:38:47,939] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [2.33, 127.0.0.1:61404]
[2022-12-16 15:39:15,810] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-16 15:39:56,787] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 15:39:59,806] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 15:39:59,806] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 15:39:59,806] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 15:40:05,573] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [2.82, 127.0.0.1:61454]
[2022-12-16 15:40:06,455] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:40:06,457] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:61459]
[2022-12-16 15:40:19,788] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.91, 127.0.0.1:61481]
[2022-12-16 15:41:07,523] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:61515]
[2022-12-16 15:41:13,603] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.09, 127.0.0.1:61534]
[2022-12-16 15:41:17,917] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.63, 127.0.0.1:61544]
[2022-12-16 15:41:31,027] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.46, 127.0.0.1:61554]
[2022-12-16 15:41:52,848] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.26, 127.0.0.1:61572]
[2022-12-16 15:42:07,602] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.26, 127.0.0.1:61585]
[2022-12-16 15:42:32,343] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:61597]
[2022-12-16 15:43:13,709] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:61624]
[2022-12-16 15:43:52,453] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:61648]
[2022-12-16 15:44:46,069] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.37, 127.0.0.1:61677]
[2022-12-16 15:44:46,374] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:61682]
[2022-12-16 15:45:26,531] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.48, 127.0.0.1:61728]
[2022-12-16 15:45:27,095] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:45:27,096] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.08, 127.0.0.1:61732]
[2022-12-16 15:45:30,159] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.29, 127.0.0.1:61732]
[2022-12-16 15:45:30,447] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:45:30,450] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:61732]
[2022-12-16 15:49:51,160] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.92, 127.0.0.1:61904]
[2022-12-16 15:50:10,924] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.06, 127.0.0.1:61924]
[2022-12-16 15:52:08,012] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.59, 127.0.0.1:62058]
[2022-12-16 15:52:41,048] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:62106]
[2022-12-16 15:53:19,537] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:62156]
[2022-12-16 15:53:25,062] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.03, 127.0.0.1:62166]
[2022-12-16 15:53:28,754] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=2 200 [0.14, 127.0.0.1:62176]
[2022-12-16 15:53:54,919] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.42, 127.0.0.1:62216]
[2022-12-16 15:56:06,150] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:62464]
[2022-12-16 15:57:06,629] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.43, 127.0.0.1:62575]
[2022-12-16 15:57:07,596] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 15:57:07,598] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.65, 127.0.0.1:62580]
[2022-12-16 15:59:40,533] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.23, 127.0.0.1:62845]
[2022-12-16 16:05:14,426] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.06, 127.0.0.1:63604]
[2022-12-16 16:05:26,862] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.44, 127.0.0.1:63627]
[2022-12-16 16:06:18,884] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.26, 127.0.0.1:63703]
[2022-12-16 16:06:33,681] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.23, 127.0.0.1:63729]
[2022-12-16 16:07:14,774] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:63781]
[2022-12-16 16:07:30,930] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:63805]
[2022-12-16 16:07:46,166] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.34, 127.0.0.1:63826]
[2022-12-16 16:07:50,928] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?page=3 200 [0.39, 127.0.0.1:63837]
[2022-12-16 16:13:03,388] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-16 16:14:35,394] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 16:14:40,776] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 16:14:40,776] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 16:14:40,776] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 16:15:15,887] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.70, 127.0.0.1:64527]
[2022-12-16 16:15:20,657] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.37, 127.0.0.1:64543]
[2022-12-16 16:18:54,159] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [3.23, 127.0.0.1:64666]
[2022-12-16 16:19:16,921] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/8 200 [12.11, 127.0.0.1:64692]
[2022-12-16 16:19:17,790] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/11 200 [12.96, 127.0.0.1:64695]
[2022-12-16 16:19:17,930] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/15 200 [0.68, 127.0.0.1:64710]
[2022-12-16 16:19:18,039] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/10 200 [13.21, 127.0.0.1:64694]
[2022-12-16 16:19:18,164] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/14 200 [13.34, 127.0.0.1:64696]
[2022-12-16 16:19:18,260] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/9 200 [13.45, 127.0.0.1:64693]
[2022-12-16 16:19:18,260] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/7 200 [13.45, 127.0.0.1:64691]
[2022-12-16 16:19:18,899] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/16 200 [0.78, 127.0.0.1:64717]
[2022-12-16 16:19:19,055] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/18 200 [0.70, 127.0.0.1:64723]
[2022-12-16 16:19:19,118] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/17 200 [0.80, 127.0.0.1:64720]
[2022-12-16 16:19:36,074] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:64735]
[2022-12-16 16:19:41,504] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?size=500 200 [0.14, 127.0.0.1:64749]
[2022-12-16 16:19:45,448] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/23 200 [0.31, 127.0.0.1:64770]
[2022-12-16 16:19:45,452] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/24 200 [0.26, 127.0.0.1:64776]
[2022-12-16 16:19:45,480] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/20 200 [0.35, 127.0.0.1:64767]
[2022-12-16 16:19:45,485] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/22 200 [0.35, 127.0.0.1:64769]
[2022-12-16 16:19:45,575] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/19 200 [0.46, 127.0.0.1:64761]
[2022-12-16 16:19:45,576] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/21 200 [0.44, 127.0.0.1:64768]
[2022-12-16 16:19:45,996] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/25 200 [0.23, 127.0.0.1:64785]
[2022-12-16 16:19:46,073] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/26 200 [0.30, 127.0.0.1:64787]
[2022-12-16 16:19:46,087] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/27 200 [0.28, 127.0.0.1:64793]
[2022-12-16 16:19:46,088] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/29 200 [0.19, 127.0.0.1:64798]
[2022-12-16 16:19:46,090] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/28 200 [0.29, 127.0.0.1:64792]
[2022-12-16 16:19:46,113] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/30 200 [0.21, 127.0.0.1:64799]
[2022-12-16 16:19:50,437] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:64810]
[2022-12-16 16:19:56,058] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:64817]
[2022-12-16 16:19:57,642] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.03, 127.0.0.1:64820]
[2022-12-16 16:20:06,305] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:64833]
[2022-12-16 16:20:06,324] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:64832]
[2022-12-16 16:20:14,384] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.18, 127.0.0.1:64846]
[2022-12-16 16:21:44,668] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.30, 127.0.0.1:64889]
[2022-12-16 16:21:58,561] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:64911]
[2022-12-16 16:22:21,324] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.66, 127.0.0.1:64932]
[2022-12-16 16:22:39,589] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/
[2022-12-16 16:22:39,591] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/?page=3 404 [6.09, 127.0.0.1:64939]
[2022-12-16 16:22:41,781] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 16:22:41,823] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [1.03, 127.0.0.1:64939]
[2022-12-16 16:22:50,192] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.16, 127.0.0.1:64953]
[2022-12-16 16:22:59,914] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 16:22:59,916] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:64965]
[2022-12-16 16:23:52,745] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:64995]
[2022-12-16 16:27:43,825] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:65205]
[2022-12-16 16:27:58,634] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.36, 127.0.0.1:65219]
[2022-12-16 16:28:29,456] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:65238]
[2022-12-16 16:28:55,288] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.41, 127.0.0.1:65258]
[2022-12-16 16:29:09,401] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:65272]
[2022-12-16 16:30:40,064] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:65314]
[2022-12-16 16:31:03,487] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.10, 127.0.0.1:65334]
[2022-12-16 16:31:50,293] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:65366]
[2022-12-16 16:32:10,662] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:65383]
[2022-12-16 16:32:21,191] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:65393]
[2022-12-16 16:32:41,287] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.08, 127.0.0.1:65408]
[2022-12-16 16:36:24,000] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.10, 127.0.0.1:49318]
[2022-12-16 16:36:40,466] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:49344]
[2022-12-16 16:41:02,992] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:49793]
[2022-12-16 16:43:24,450] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:49876]
[2022-12-16 16:43:58,071] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:49905]
[2022-12-16 16:47:33,949] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.36, 127.0.0.1:50031]
[2022-12-16 16:47:33,958] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.37, 127.0.0.1:50030]
[2022-12-16 16:47:42,110] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.27, 127.0.0.1:50041]
[2022-12-16 16:47:45,077] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=38 200 [0.18, 127.0.0.1:50048]
[2022-12-16 16:48:15,683] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.25, 127.0.0.1:50068]
[2022-12-16 16:48:19,579] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:50076]
[2022-12-16 16:48:40,549] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:50092]
[2022-12-16 16:50:31,913] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:50162]
[2022-12-16 16:50:48,483] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search=%E6%A8%A1%E5%9D%972 200 [0.39, 127.0.0.1:50179]
[2022-12-16 16:50:54,291] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search= 200 [0.06, 127.0.0.1:50185]
[2022-12-16 16:51:01,558] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:50199]
[2022-12-16 16:51:54,548] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.10, 127.0.0.1:50232]
[2022-12-16 16:52:57,280] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 16:52:57,282] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.29, 127.0.0.1:50270]
[2022-12-16 16:53:05,753] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.59, 127.0.0.1:50280]
[2022-12-16 16:53:06,058] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 16:53:06,060] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.08, 127.0.0.1:50280]
[2022-12-16 16:53:22,643] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search=%E6%A8%A1%E5%9D%972 200 [0.29, 127.0.0.1:50289]
[2022-12-16 16:53:22,859] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 16:53:22,860] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:50289]
[2022-12-16 16:53:59,961] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.10, 127.0.0.1:50313]
[2022-12-16 16:54:05,016] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search=%E6%A8%A1%E5%9D%972 200 [0.09, 127.0.0.1:50321]
[2022-12-16 16:54:07,855] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search= 200 [0.13, 127.0.0.1:50325]
[2022-12-16 16:54:47,182] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:50343]
[2022-12-16 16:54:51,788] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.08, 127.0.0.1:50353]
[2022-12-16 16:55:06,255] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:50367]
[2022-12-16 16:55:20,791] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search=%E9%A1%B9%E7%9B%AEk 200 [0.11, 127.0.0.1:50382]
[2022-12-16 16:55:23,360] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search= 200 [0.11, 127.0.0.1:50385]
[2022-12-16 16:55:29,039] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search=%E6%96%B0%E5%A2%9E 200 [0.09, 127.0.0.1:50394]
[2022-12-16 16:55:31,961] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search= 200 [0.06, 127.0.0.1:50401]
[2022-12-16 16:55:35,807] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search=%2Fcases%2F%7Bid%7D 200 [0.11, 127.0.0.1:50407]
[2022-12-16 16:55:40,812] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search=%2Fcases%2F 200 [0.09, 127.0.0.1:50416]
[2022-12-16 16:55:45,826] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search=%2Fcases 200 [0.16, 127.0.0.1:50428]
[2022-12-16 16:55:50,997] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search=%2Fcases%2F 200 [0.11, 127.0.0.1:50435]
[2022-12-16 16:55:53,723] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/?search= 200 [0.10, 127.0.0.1:50439]
[2022-12-16 16:56:05,785] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:50453]
[2022-12-16 16:56:05,832] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:50454]
[2022-12-16 16:56:12,301] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.11, 127.0.0.1:50462]
[2022-12-16 16:56:39,945] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.17, 127.0.0.1:50476]
[2022-12-16 16:56:43,617] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:50480]
[2022-12-16 16:58:59,281] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.50, 127.0.0.1:50552]
[2022-12-16 16:58:59,519] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/32
[2022-12-16 16:58:59,535] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/32 404 [0.73, 127.0.0.1:50553]
[2022-12-16 16:59:01,997] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.61, 127.0.0.1:50567]
[2022-12-16 16:59:02,069] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/32
[2022-12-16 16:59:02,072] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/32 404 [0.68, 127.0.0.1:50568]
[2022-12-16 16:59:10,248] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.40, 127.0.0.1:50579]
[2022-12-16 16:59:13,065] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.24, 127.0.0.1:50586]
[2022-12-16 16:59:13,475] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.34, 127.0.0.1:50589]
[2022-12-16 16:59:17,607] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:50598]
[2022-12-16 16:59:17,683] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:50599]
[2022-12-16 17:01:40,330] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:50673]
[2022-12-16 17:01:40,490] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:50677]
[2022-12-16 17:01:40,683] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:50684]
[2022-12-16 17:01:40,714] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:50682]
[2022-12-16 17:01:40,885] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.09, 127.0.0.1:50688]
[2022-12-16 17:02:43,329] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:50733]
[2022-12-16 17:02:43,366] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:50732]
[2022-12-16 17:02:43,412] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:50736]
[2022-12-16 17:02:43,545] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:50738]
[2022-12-16 17:02:44,160] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.15, 127.0.0.1:50740]
[2022-12-16 17:45:42,803] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 17:45:42,804] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.10, 127.0.0.1:51833]
[2022-12-16 17:45:47,739] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [2.81, 127.0.0.1:51833]
[2022-12-16 17:45:47,938] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 17:45:47,939] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:51836]
[2022-12-16 17:45:48,180] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.41, 127.0.0.1:51833]
[2022-12-16 17:45:48,282] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 17:45:48,283] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.02, 127.0.0.1:51833]
[2022-12-16 17:51:34,473] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:52000]
[2022-12-16 17:51:34,658] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:52003]
[2022-12-16 17:51:35,073] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.12, 127.0.0.1:52006]
[2022-12-16 17:51:35,308] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.03, 127.0.0.1:52011]
[2022-12-16 17:51:39,677] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.06, 127.0.0.1:52016]
[2022-12-16 17:51:46,542] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:52025]
[2022-12-16 17:51:46,609] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:52027]
[2022-12-16 17:51:46,739] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.07, 127.0.0.1:52034]
[2022-12-16 17:51:47,025] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.05, 127.0.0.1:52038]
[2022-12-16 17:51:52,550] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:52045]
[2022-12-16 17:52:00,045] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:52056]
[2022-12-16 17:52:00,052] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:52057]
[2022-12-16 17:52:00,300] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/33 200 [0.12, 127.0.0.1:52063]
[2022-12-16 17:52:00,487] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.07, 127.0.0.1:52068]
[2022-12-16 17:52:08,138] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.08, 127.0.0.1:52076]
[2022-12-16 17:52:16,178] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:52087]
[2022-12-16 17:52:16,264] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:52088]
[2022-12-16 17:52:16,374] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/33 200 [0.06, 127.0.0.1:52093]
[2022-12-16 17:52:16,719] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.10, 127.0.0.1:52096]
[2022-12-16 17:52:18,753] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:52102]
[2022-12-16 17:52:35,910] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:52116]
[2022-12-16 17:52:35,931] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:52117]
[2022-12-16 17:52:36,067] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.03, 127.0.0.1:52123]
[2022-12-16 17:52:36,400] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.10, 127.0.0.1:52127]
[2022-12-16 17:54:32,362] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:52187]
[2022-12-16 17:54:32,581] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.10, 127.0.0.1:52190]
[2022-12-16 17:54:32,751] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.09, 127.0.0.1:52194]
[2022-12-16 17:54:33,066] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.09, 127.0.0.1:52197]
[2022-12-16 17:59:04,391] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:52541]
[2022-12-16 17:59:04,433] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:52542]
[2022-12-16 17:59:05,142] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.19, 127.0.0.1:52550]
[2022-12-16 17:59:05,150] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.20, 127.0.0.1:52549]
[2022-12-16 17:59:51,151] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.22, 127.0.0.1:52617]
[2022-12-16 17:59:51,218] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [1.39, 127.0.0.1:52613]
[2022-12-16 17:59:52,661] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [1.49, 127.0.0.1:52621]
[2022-12-16 17:59:53,372] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [1.88, 127.0.0.1:52626]
[2022-12-16 17:59:55,767] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.37, 127.0.0.1:52639]
[2022-12-16 17:59:56,073] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.67, 127.0.0.1:52640]
[2022-12-16 18:00:36,166] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:52707]
[2022-12-16 18:00:36,359] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.09, 127.0.0.1:52711]
[2022-12-16 18:00:36,473] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:52714]
[2022-12-16 18:00:36,595] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:52717]
[2022-12-16 18:00:36,860] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.14, 127.0.0.1:52720]
[2022-12-16 18:00:37,172] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.14, 127.0.0.1:52724]
[2022-12-16 18:00:39,387] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:52736]
[2022-12-16 18:00:39,629] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.41, 127.0.0.1:52737]
[2022-12-16 18:03:20,211] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:52970]
[2022-12-16 18:03:20,423] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:52977]
[2022-12-16 18:03:20,447] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:52974]
[2022-12-16 18:03:20,569] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:52980]
[2022-12-16 18:03:20,992] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.09, 127.0.0.1:52984]
[2022-12-16 18:03:21,288] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.08, 127.0.0.1:52988]
[2022-12-16 18:03:23,347] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:53001]
[2022-12-16 18:03:23,404] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:53002]
[2022-12-16 18:08:56,746] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:53596]
[2022-12-16 18:08:56,882] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:53599]
[2022-12-16 18:08:56,964] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:53603]
[2022-12-16 18:08:57,166] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:53606]
[2022-12-16 18:08:57,204] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.14, 127.0.0.1:53610]
[2022-12-16 18:08:57,556] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.16, 127.0.0.1:53615]
[2022-12-16 18:09:10,368] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:53640]
[2022-12-16 18:09:10,450] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.58, 127.0.0.1:53637]
[2022-12-16 18:09:10,643] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.26, 127.0.0.1:53644]
[2022-12-16 18:09:10,680] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.23, 127.0.0.1:53647]
[2022-12-16 18:09:11,270] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.30, 127.0.0.1:53653]
[2022-12-16 18:09:11,653] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.68, 127.0.0.1:53654]
[2022-12-16 18:09:20,551] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.31, 127.0.0.1:53675]
[2022-12-16 18:09:21,019] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.45, 127.0.0.1:53684]
[2022-12-16 18:09:21,035] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.58, 127.0.0.1:53678]
[2022-12-16 18:09:21,191] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:53686]
[2022-12-16 18:09:21,316] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.12, 127.0.0.1:53689]
[2022-12-16 18:09:22,002] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.50, 127.0.0.1:53693]
[2022-12-16 18:09:48,207] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:53733]
[2022-12-16 18:09:48,502] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:53740]
[2022-12-16 18:09:48,523] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:53737]
[2022-12-16 18:09:48,743] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:53745]
[2022-12-16 18:09:48,858] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.10, 127.0.0.1:53747]
[2022-12-16 18:09:49,192] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.09, 127.0.0.1:53752]
[2022-12-16 18:09:53,011] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:53765]
[2022-12-16 18:09:53,060] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:53766]
[2022-12-16 18:10:26,258] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.27, 127.0.0.1:53823]
[2022-12-16 18:10:26,264] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:53824]
[2022-12-16 18:13:45,842] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:54146]
[2022-12-16 18:13:46,052] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:54151]
[2022-12-16 18:13:57,632] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.19, 127.0.0.1:54170]
[2022-12-16 18:13:57,654] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:54171]
[2022-12-16 18:13:58,230] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.22, 127.0.0.1:54175]
[2022-12-16 18:13:58,383] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.07, 127.0.0.1:54179]
[2022-12-16 18:21:51,652] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.47, 127.0.0.1:54637]
[2022-12-16 18:21:57,510] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:54646]
[2022-12-16 18:21:57,572] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:54647]
[2022-12-16 18:22:05,918] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.29, 127.0.0.1:54660]
[2022-12-16 18:23:39,066] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [3.11, 127.0.0.1:54702]
[2022-12-16 18:23:42,572] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:54708]
[2022-12-16 18:24:00,881] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.22, 127.0.0.1:54726]
[2022-12-16 18:24:00,944] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:54727]
[2022-12-16 18:24:01,131] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.12, 127.0.0.1:54731]
[2022-12-16 18:24:01,562] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.24, 127.0.0.1:54735]
[2022-12-16 18:32:15,659] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 18:32:15,716] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [1.86, 127.0.0.1:54937]
[2022-12-16 18:32:42,153] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [4.24, 127.0.0.1:54946]
[2022-12-16 18:32:42,765] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-16 18:32:42,767] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.04, 127.0.0.1:54946]
[2022-12-16 18:34:38,894] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:55001]
[2022-12-16 18:34:39,179] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:55008]
[2022-12-16 18:34:39,267] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.34, 127.0.0.1:55005]
[2022-12-16 18:34:39,611] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.34, 127.0.0.1:55012]
[2022-12-16 18:34:39,627] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.34, 127.0.0.1:55013]
[2022-12-16 18:34:39,771] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.18, 127.0.0.1:55018]
[2022-12-16 18:35:30,478] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:55053]
[2022-12-16 18:35:30,540] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:55054]
[2022-12-16 18:35:31,019] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.16, 127.0.0.1:55059]
[2022-12-16 18:35:31,250] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.08, 127.0.0.1:55063]
[2022-12-16 18:35:36,171] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:55070]
[2022-12-16 18:35:50,893] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.29, 127.0.0.1:55083]
[2022-12-16 18:35:51,013] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.41, 127.0.0.1:55084]
[2022-12-16 18:35:51,222] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.19, 127.0.0.1:55089]
[2022-12-16 18:35:51,478] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.14, 127.0.0.1:55092]
[2022-12-16 18:35:55,127] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:55099]
[2022-12-16 18:42:53,038] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:55285]
[2022-12-16 18:42:53,176] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.26, 127.0.0.1:55286]
[2022-12-16 18:42:53,447] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:55289]
[2022-12-16 18:42:54,202] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.28, 127.0.0.1:55292]
[2022-12-16 18:42:54,315] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.43, 127.0.0.1:55291]
[2022-12-16 18:43:27,554] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.21, 127.0.0.1:55323]
[2022-12-16 18:43:27,709] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.34, 127.0.0.1:55325]
[2022-12-16 18:43:27,953] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.14, 127.0.0.1:55328]
[2022-12-16 18:43:28,213] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.09, 127.0.0.1:55331]
[2022-12-16 18:48:36,318] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.19, 127.0.0.1:55456]
[2022-12-16 18:48:36,337] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:55457]
[2022-12-16 18:48:36,851] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.25, 127.0.0.1:55461]
[2022-12-16 18:48:37,163] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.23, 127.0.0.1:55465]
[2022-12-16 18:48:59,966] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:55479]
[2022-12-16 18:49:00,176] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:55482]
[2022-12-16 18:49:00,439] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:55486]
[2022-12-16 18:49:00,741] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.08, 127.0.0.1:55489]
[2022-12-16 18:49:15,123] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:55504]
[2022-12-16 18:49:15,394] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:55507]
[2022-12-16 18:49:15,531] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:55511]
[2022-12-16 18:49:15,896] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.14, 127.0.0.1:55514]
[2022-12-16 18:49:23,773] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:55523]
[2022-12-16 18:49:49,910] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [26.06, 127.0.0.1:55526]
[2022-12-16 18:49:50,051] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.20, 127.0.0.1:55536]
[2022-12-16 18:49:50,129] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:55550]
[2022-12-16 18:49:50,507] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.26, 127.0.0.1:55557]
[2022-12-16 18:49:50,540] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.29, 127.0.0.1:55558]
[2022-12-16 18:49:50,546] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.26, 127.0.0.1:55563]
[2022-12-16 18:49:50,742] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:55568]
[2022-12-16 18:49:50,915] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:55571]
[2022-12-16 18:49:50,991] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.14, 127.0.0.1:55574]
[2022-12-16 18:49:51,493] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.25, 127.0.0.1:55579]
[2022-12-16 18:49:51,509] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.19, 127.0.0.1:55582]
[2022-12-16 18:50:04,102] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:55593]
[2022-12-16 18:50:04,365] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:55596]
[2022-12-16 18:50:04,428] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.04, 127.0.0.1:55600]
[2022-12-16 18:50:04,769] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.07, 127.0.0.1:55603]
[2022-12-16 18:50:15,939] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:55626]
[2022-12-16 18:50:16,030] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:55627]
[2022-12-16 18:50:16,190] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.10, 127.0.0.1:55632]
[2022-12-16 18:50:16,273] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.18, 127.0.0.1:55633]
[2022-12-16 18:51:28,576] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:55715]
[2022-12-16 18:51:28,715] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:55718]
[2022-12-16 18:51:29,445] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:55723]
[2022-12-16 18:51:29,841] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.17, 127.0.0.1:55726]
[2022-12-16 18:53:04,534] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.20, 127.0.0.1:55850]
[2022-12-16 18:53:04,642] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:55851]
[2022-12-16 18:53:05,412] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.12, 127.0.0.1:55856]
[2022-12-16 18:53:05,734] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.18, 127.0.0.1:55859]
[2022-12-16 18:56:15,655] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:56092]
[2022-12-16 18:56:15,898] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:56096]
[2022-12-16 18:56:16,414] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.12, 127.0.0.1:56100]
[2022-12-16 18:56:16,702] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.16, 127.0.0.1:56103]
[2022-12-16 18:57:25,327] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 18:57:25,329] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.13, 127.0.0.1:56179]
[2022-12-16 18:57:25,936] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.37, 127.0.0.1:56190]
[2022-12-16 18:57:34,918] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.51, 127.0.0.1:56204]
[2022-12-16 18:57:34,956] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.55, 127.0.0.1:56203]
[2022-12-16 18:57:35,570] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.63, 127.0.0.1:56209]
[2022-12-16 18:57:35,710] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.46, 127.0.0.1:56212]
[2022-12-16 18:59:36,393] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:56366]
[2022-12-16 18:59:36,762] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:56369]
[2022-12-16 18:59:36,991] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.10, 127.0.0.1:56374]
[2022-12-16 18:59:37,260] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.07, 127.0.0.1:56377]
[2022-12-16 18:59:39,775] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.44, 127.0.0.1:56380]
[2022-12-16 18:59:40,039] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 18:59:40,041] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.05, 127.0.0.1:56380]
[2022-12-16 18:59:59,303] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:56409]
[2022-12-16 18:59:59,602] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:56412]
[2022-12-16 18:59:59,800] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:56416]
[2022-12-16 19:00:00,135] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.12, 127.0.0.1:56419]
[2022-12-16 19:01:43,913] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:56552]
[2022-12-16 19:01:44,145] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:56555]
[2022-12-16 19:01:44,421] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.14, 127.0.0.1:56559]
[2022-12-16 19:01:44,636] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.05, 127.0.0.1:56562]
[2022-12-16 19:02:07,169] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:56595]
[2022-12-16 19:02:07,465] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:56598]
[2022-12-16 19:02:07,636] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.06, 127.0.0.1:56601]
[2022-12-16 19:02:07,996] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.09, 127.0.0.1:56606]
[2022-12-16 19:02:17,845] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:56623]
[2022-12-16 19:02:18,087] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:56627]
[2022-12-16 19:02:18,224] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.05, 127.0.0.1:56631]
[2022-12-16 19:02:18,551] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.07, 127.0.0.1:56634]
[2022-12-16 19:02:26,308] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.24, 127.0.0.1:56653]
[2022-12-16 19:02:26,356] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:56654]
[2022-12-16 19:02:27,354] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.19, 127.0.0.1:56666]
[2022-12-16 19:02:27,382] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.22, 127.0.0.1:56667]
[2022-12-16 19:03:49,673] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:56773]
[2022-12-16 19:03:49,859] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.08, 127.0.0.1:56776]
[2022-12-16 19:03:50,190] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:56780]
[2022-12-16 19:03:50,459] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.05, 127.0.0.1:56784]
[2022-12-16 19:04:12,122] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:56813]
[2022-12-16 19:04:12,279] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:56816]
[2022-12-16 19:04:12,535] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:56819]
[2022-12-16 19:04:12,816] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.06, 127.0.0.1:56824]
[2022-12-16 19:05:15,619] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:56900]
[2022-12-16 19:05:15,950] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:56904]
[2022-12-16 19:05:16,014] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.04, 127.0.0.1:56907]
[2022-12-16 19:05:16,395] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.11, 127.0.0.1:56911]
[2022-12-16 19:06:20,818] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:56992]
[2022-12-16 19:06:21,133] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:56996]
[2022-12-16 19:06:21,317] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.11, 127.0.0.1:57000]
[2022-12-16 19:06:21,582] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.11, 127.0.0.1:57004]
[2022-12-16 19:09:22,728] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.19, 127.0.0.1:57439]
[2022-12-16 19:09:22,883] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.29, 127.0.0.1:57442]
[2022-12-16 19:09:23,022] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:57446]
[2022-12-16 19:09:23,557] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.29, 127.0.0.1:57449]
[2022-12-16 19:10:18,704] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:57529]
[2022-12-16 19:10:18,985] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:57532]
[2022-12-16 19:10:19,098] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.09, 127.0.0.1:57536]
[2022-12-16 19:10:19,420] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.11, 127.0.0.1:57539]
[2022-12-16 19:10:35,325] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:57571]
[2022-12-16 19:10:35,569] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:57574]
[2022-12-16 19:10:35,644] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.06, 127.0.0.1:57578]
[2022-12-16 19:10:36,015] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.12, 127.0.0.1:57581]
[2022-12-16 19:10:40,289] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.27, 127.0.0.1:57595]
[2022-12-16 19:10:40,396] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.35, 127.0.0.1:57596]
[2022-12-16 19:10:41,324] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.11, 127.0.0.1:57606]
[2022-12-16 19:10:41,396] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.16, 127.0.0.1:57609]
[2022-12-16 19:15:22,189] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:57970]
[2022-12-16 19:15:22,498] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:57973]
[2022-12-16 19:15:22,836] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.10, 127.0.0.1:57977]
[2022-12-16 19:15:23,032] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.08, 127.0.0.1:57982]
[2022-12-16 19:15:23,361] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:57986]
[2022-12-16 19:15:23,745] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:57989]
[2022-12-16 19:15:24,555] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.47, 127.0.0.1:57997]
[2022-12-16 19:15:24,831] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.75, 127.0.0.1:57996]
[2022-12-16 19:17:09,217] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:58128]
[2022-12-16 19:17:09,466] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:58131]
[2022-12-16 19:17:10,077] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.22, 127.0.0.1:58139]
[2022-12-16 19:17:10,124] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.26, 127.0.0.1:58141]
[2022-12-16 19:19:05,636] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:58291]
[2022-12-16 19:19:05,736] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:58294]
[2022-12-16 19:19:06,185] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.24, 127.0.0.1:58298]
[2022-12-16 19:19:06,483] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.25, 127.0.0.1:58302]
[2022-12-16 19:19:42,175] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:58344]
[2022-12-16 19:19:45,510] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.21, 127.0.0.1:58353]
[2022-12-16 19:19:45,510] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:58354]
[2022-12-16 19:19:45,881] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.29, 127.0.0.1:58359]
[2022-12-16 19:19:46,185] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.27, 127.0.0.1:58362]
[2022-12-16 19:22:26,982] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:58694]
[2022-12-16 19:22:27,205] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:58697]
[2022-12-16 19:22:27,276] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.05, 127.0.0.1:58701]
[2022-12-16 19:22:27,579] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.04, 127.0.0.1:58704]
[2022-12-16 19:22:39,406] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:58728]
[2022-12-16 19:22:39,477] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:58729]
[2022-12-16 19:22:40,588] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.18, 127.0.0.1:58740]
[2022-12-16 19:22:40,637] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.23, 127.0.0.1:58741]
[2022-12-16 19:23:12,515] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:58826]
[2022-12-16 19:23:12,671] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:58830]
[2022-12-16 19:23:13,134] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.17, 127.0.0.1:58838]
[2022-12-16 19:23:13,375] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.11, 127.0.0.1:58841]
[2022-12-16 19:23:33,782] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.51, 127.0.0.1:58885]
[2022-12-16 19:23:34,667] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.38, 127.0.0.1:58886]
[2022-12-16 19:23:35,724] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.73, 127.0.0.1:58898]
[2022-12-16 19:23:35,799] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.49, 127.0.0.1:58901]
[2022-12-16 19:23:46,279] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.76, 127.0.0.1:58931]
[2022-12-16 19:23:46,444] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.92, 127.0.0.1:58933]
[2022-12-16 19:23:46,635] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.17, 127.0.0.1:58939]
[2022-12-16 19:23:46,746] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.22, 127.0.0.1:58943]
[2022-12-16 19:24:40,078] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:58976]
[2022-12-16 19:28:58,256] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 19:28:58,256] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-16 19:28:58,580] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [8.90, 127.0.0.1:59102]
[2022-12-16 19:28:58,581] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [9.15, 127.0.0.1:59101]
[2022-12-16 19:30:08,430] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.66, 127.0.0.1:59152]
[2022-12-16 19:30:08,433] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.67, 127.0.0.1:59151]
[2022-12-16 19:30:08,614] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.12, 127.0.0.1:59157]
[2022-12-16 19:30:09,029] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.05, 127.0.0.1:59160]
[2022-12-16 19:30:24,648] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/34
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 567, in put
    return Response(serialize.data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py", line 46, in get_method_response
    return obj.get_method_display()
AttributeError: 'collections.OrderedDict' object has no attribute 'get_method_display'
[2022-12-16 19:30:25,534] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/34 500 [10.93, 127.0.0.1:59171]
[2022-12-16 19:30:53,826] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.86, 127.0.0.1:59206]
[2022-12-16 19:30:58,745] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:59222]
[2022-12-16 19:30:58,820] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.26, 127.0.0.1:59223]
[2022-12-16 19:30:59,001] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.10, 127.0.0.1:59228]
[2022-12-16 19:30:59,330] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.12, 127.0.0.1:59231]
[2022-12-16 19:31:12,753] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/34
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 567, in put
    return Response(serialize.data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py", line 46, in get_method_response
    return obj.get_method_display()
AttributeError: 'collections.OrderedDict' object has no attribute 'get_method_display'
[2022-12-16 19:31:12,768] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/34 500 [0.93, 127.0.0.1:59253]
[2022-12-16 19:31:57,242] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:59281]
[2022-12-16 19:32:06,330] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:59294]
[2022-12-16 19:32:06,480] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:59295]
[2022-12-16 19:32:06,598] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.10, 127.0.0.1:59301]
[2022-12-16 19:32:06,890] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.08, 127.0.0.1:59305]
[2022-12-16 19:33:11,586] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/34
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 567, in put
    return Response(serialize.data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py", line 46, in get_method_response
    return obj.get_method_display()
AttributeError: 'collections.OrderedDict' object has no attribute 'get_method_display'
[2022-12-16 19:33:11,601] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/34 500 [0.66, 127.0.0.1:59381]
[2022-12-16 19:34:05,343] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:59450]
[2022-12-16 19:34:08,690] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:59458]
[2022-12-16 19:34:08,737] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:59459]
[2022-12-16 19:34:26,438] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project=36 200 [0.20, 127.0.0.1:59477]
[2022-12-16 19:34:55,320] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.25, 127.0.0.1:59493]
[2022-12-16 19:35:03,999] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:59506]
[2022-12-16 19:35:08,682] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:59517]
[2022-12-16 19:35:08,709] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:59516]
[2022-12-16 19:35:08,856] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.07, 127.0.0.1:59522]
[2022-12-16 19:35:09,168] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.08, 127.0.0.1:59525]
[2022-12-16 19:35:44,198] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/34
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 567, in put
    return Response(serialize.data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py", line 46, in get_method_response
    return obj.get_method_display()
AttributeError: 'collections.OrderedDict' object has no attribute 'get_method_display'
[2022-12-16 19:35:44,198] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/34 500 [0.44, 127.0.0.1:59548]
[2022-12-16 19:35:51,445] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:59556]
[2022-12-16 19:35:55,540] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:59560]
[2022-12-16 19:35:55,770] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.09, 127.0.0.1:59563]
[2022-12-16 19:35:56,233] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.13, 127.0.0.1:59571]
[2022-12-16 19:35:56,261] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.16, 127.0.0.1:59570]
[2022-12-16 19:36:23,379] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/34
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 567, in put
    return Response(serialize.data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py", line 46, in get_method_response
    return obj.get_method_display()
AttributeError: 'collections.OrderedDict' object has no attribute 'get_method_display'
[2022-12-16 19:36:23,387] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/34 500 [0.47, 127.0.0.1:59610]
[2022-12-16 19:44:26,669] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-16 19:46:20,474] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 19:46:26,954] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 19:46:26,985] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 19:46:26,985] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 19:46:45,789] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [9.65, 127.0.0.1:60373]
[2022-12-16 19:46:50,787] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 19:46:50,790] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [1.23, 127.0.0.1:60380]
[2022-12-16 19:47:07,183] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/34
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 569, in put
    return Response(serialize.data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 255, in data
    self._data = self.to_representation(self.validated_data)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\fields.py", line 1838, in to_representation
    return method(value)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py", line 46, in get_method_response
    return obj.get_method_display()
AttributeError: 'collections.OrderedDict' object has no attribute 'get_method_display'
[2022-12-16 19:47:07,198] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /cases/34 500 [2.54, 127.0.0.1:60386]
[2022-12-16 19:48:38,537] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.91, 127.0.0.1:60430]
[2022-12-16 19:48:45,593] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 19:48:45,595] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:60437]
[2022-12-16 19:56:13,030] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.71, 127.0.0.1:60690]
[2022-12-16 19:56:13,264] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.91, 127.0.0.1:60691]
[2022-12-16 19:56:14,263] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.58, 127.0.0.1:60701]
[2022-12-16 19:56:14,333] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.60, 127.0.0.1:60704]
[2022-12-16 19:56:20,209] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.60, 127.0.0.1:60714]
[2022-12-16 19:56:35,210] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.37, 127.0.0.1:60728]
[2022-12-16 19:56:44,841] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-16 19:57:07,887] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-16 19:57:10,831] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-16 19:57:10,831] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-16 19:57:10,831] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-16 19:57:41,491] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.41, 127.0.0.1:60775]
[2022-12-16 19:57:51,674] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.48, 127.0.0.1:60784]
[2022-12-16 19:58:03,751] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.34, 127.0.0.1:60797]
[2022-12-16 19:58:12,638] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.36, 127.0.0.1:60808]
[2022-12-16 19:58:21,133] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.42, 127.0.0.1:60816]
[2022-12-16 19:58:28,493] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:60827]
[2022-12-16 19:58:33,153] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:60831]
[2022-12-16 19:58:41,195] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:60839]
[2022-12-16 19:58:52,130] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.67, 127.0.0.1:60847]
[2022-12-16 19:58:52,649] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 19:58:52,651] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.14, 127.0.0.1:60847]
[2022-12-16 19:59:05,976] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.32, 127.0.0.1:60855]
[2022-12-16 19:59:06,342] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 19:59:06,343] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:60855]
[2022-12-16 19:59:12,595] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/34 200 [0.42, 127.0.0.1:60864]
[2022-12-16 19:59:18,822] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.36, 127.0.0.1:60868]
[2022-12-16 19:59:23,472] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 19:59:23,473] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:60871]
[2022-12-16 19:59:26,764] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.37, 127.0.0.1:60878]
[2022-12-16 19:59:26,893] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.49, 127.0.0.1:60879]
[2022-12-16 19:59:27,340] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.36, 127.0.0.1:60884]
[2022-12-16 19:59:27,774] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.24, 127.0.0.1:60888]
[2022-12-16 20:00:17,652] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/34 200 [0.42, 127.0.0.1:60912]
[2022-12-16 20:00:21,348] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:60920]
[2022-12-16 20:00:24,749] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:60928]
[2022-12-16 20:00:24,841] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:60929]
[2022-12-16 20:00:24,997] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.06, 127.0.0.1:60935]
[2022-12-16 20:00:25,250] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.08, 127.0.0.1:60939]
[2022-12-16 20:02:07,519] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:60990]
[2022-12-16 20:02:07,883] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.33, 127.0.0.1:60994]
[2022-12-16 20:02:08,101] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.22, 127.0.0.1:60997]
[2022-12-16 20:02:08,429] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.22, 127.0.0.1:61001]
[2022-12-16 20:04:51,402] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.20, 127.0.0.1:61163]
[2022-12-16 20:04:51,549] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:61166]
[2022-12-16 20:04:51,814] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.25, 127.0.0.1:61169]
[2022-12-16 20:04:52,057] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.15, 127.0.0.1:61173]
[2022-12-16 20:13:32,870] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.37, 127.0.0.1:61430]
[2022-12-16 20:13:33,501] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.99, 127.0.0.1:61431]
[2022-12-16 20:13:34,546] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.22, 127.0.0.1:61441]
[2022-12-16 20:13:34,681] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.36, 127.0.0.1:61440]
[2022-12-16 20:13:47,108] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.61, 127.0.0.1:61451]
[2022-12-16 20:13:56,062] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.20, 127.0.0.1:61465]
[2022-12-16 20:13:56,191] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.32, 127.0.0.1:61466]
[2022-12-16 20:13:57,023] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.31, 127.0.0.1:61471]
[2022-12-16 20:13:57,349] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.33, 127.0.0.1:61474]
[2022-12-16 20:14:19,235] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:61486]
[2022-12-16 20:14:21,481] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:61490]
[2022-12-16 20:14:21,807] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:61493]
[2022-12-16 20:14:22,400] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.27, 127.0.0.1:61500]
[2022-12-16 20:14:22,447] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.31, 127.0.0.1:61501]
[2022-12-16 20:16:39,762] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:61575]
[2022-12-16 20:16:44,282] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:61584]
[2022-12-16 20:16:44,356] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:61585]
[2022-12-16 20:17:06,309] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:61600]
[2022-12-16 20:17:11,006] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:61609]
[2022-12-16 20:17:11,040] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:61610]
[2022-12-16 20:17:11,285] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.17, 127.0.0.1:61616]
[2022-12-16 20:17:11,666] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.27, 127.0.0.1:61621]
[2022-12-16 20:17:25,998] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [1.94, 127.0.0.1:61630]
[2022-12-16 20:17:26,618] [log.py:241] [log:log_response] [WARNING]- Not Found: /relation
[2022-12-16 20:17:26,619] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relation 404 [0.26, 127.0.0.1:61632]
[2022-12-16 20:17:29,360] [log.py:241] [log:log_response] [WARNING]- Not Found: /jquery.min.js
[2022-12-16 20:17:29,361] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /jquery.min.js 404 [0.03, 127.0.0.1:61633]
[2022-12-16 20:17:31,923] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /relations/ 200 [0.81, 127.0.0.1:61633]
[2022-12-16 20:17:33,276] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-16 20:17:33,277] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:61637]
[2022-12-16 20:20:00,990] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 20:20:00,992] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:61707]
[2022-12-16 20:20:47,666] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:61728]
[2022-12-16 20:20:47,830] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:61731]
[2022-12-16 20:20:48,339] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.11, 127.0.0.1:61735]
[2022-12-16 20:20:48,802] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.21, 127.0.0.1:61738]
[2022-12-16 20:21:01,979] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:61750]
[2022-12-16 20:21:04,735] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:61758]
[2022-12-16 20:21:04,766] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:61759]
[2022-12-16 20:21:05,589] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.47, 127.0.0.1:61769]
[2022-12-16 20:21:05,836] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.96, 127.0.0.1:61765]
[2022-12-16 20:21:37,865] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:61793]
[2022-12-16 20:21:38,149] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:61796]
[2022-12-16 20:21:38,211] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.03, 127.0.0.1:61800]
[2022-12-16 20:21:38,610] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.14, 127.0.0.1:61803]
[2022-12-16 20:22:10,713] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:61822]
[2022-12-16 20:22:10,974] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:61825]
[2022-12-16 20:22:11,100] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.11, 127.0.0.1:61829]
[2022-12-16 20:22:11,391] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.10, 127.0.0.1:61832]
[2022-12-16 20:22:20,843] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:61843]
[2022-12-16 20:22:22,290] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:61847]
[2022-12-16 20:22:22,610] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:61850]
[2022-12-16 20:27:07,588] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:61976]
[2022-12-16 20:27:09,203] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:61981]
[2022-12-16 20:27:09,607] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:61984]
[2022-12-16 20:27:15,297] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:61990]
[2022-12-16 20:27:19,044] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:61997]
[2022-12-16 20:27:19,343] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.06, 127.0.0.1:62000]
[2022-12-16 20:27:19,796] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.13, 127.0.0.1:62007]
[2022-12-16 20:27:19,820] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.15, 127.0.0.1:62008]
[2022-12-16 20:30:09,818] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:62105]
[2022-12-16 20:30:12,752] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:62112]
[2022-12-16 20:30:13,111] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.09, 127.0.0.1:62115]
[2022-12-16 20:30:15,060] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:62120]
[2022-12-16 20:30:17,726] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:62124]
[2022-12-16 20:30:18,130] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:62127]
[2022-12-16 20:30:18,550] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.11, 127.0.0.1:62134]
[2022-12-16 20:30:18,612] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.17, 127.0.0.1:62135]
[2022-12-16 20:31:31,808] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:62170]
[2022-12-16 20:31:31,999] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.09, 127.0.0.1:62173]
[2022-12-16 20:31:32,159] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.08, 127.0.0.1:62177]
[2022-12-16 20:31:32,457] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.07, 127.0.0.1:62180]
[2022-12-16 20:31:35,844] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:62187]
[2022-12-16 20:31:39,271] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:62192]
[2022-12-16 20:31:39,639] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.07, 127.0.0.1:62195]
[2022-12-16 20:31:40,135] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.11, 127.0.0.1:62203]
[2022-12-16 20:31:40,151] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/34 200 [0.12, 127.0.0.1:62202]
[2022-12-16 20:31:46,455] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:62211]
[2022-12-16 20:31:53,562] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:62221]
[2022-12-16 20:31:53,649] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:62222]
[2022-12-16 20:31:53,781] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/33 200 [0.09, 127.0.0.1:62228]
[2022-12-16 20:31:54,095] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.10, 127.0.0.1:62232]
[2022-12-16 20:31:59,417] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.07, 127.0.0.1:62240]
[2022-12-16 20:32:13,387] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.20, 127.0.0.1:62251]
[2022-12-16 20:32:13,410] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:62252]
[2022-12-16 20:32:13,992] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.13, 127.0.0.1:62260]
[2022-12-16 20:32:13,992] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.13, 127.0.0.1:62261]
[2022-12-16 20:32:22,257] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 20:32:22,259] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.03, 127.0.0.1:62268]
[2022-12-16 20:32:25,999] [log.py:241] [log:log_response] [WARNING]- Not Found: /relations/jquery.min.js
[2022-12-16 20:32:26,001] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /relations/jquery.min.js 404 [0.03, 127.0.0.1:62270]
[2022-12-16 20:32:40,625] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:62288]
[2022-12-16 20:32:41,988] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:62296]
[2022-12-16 20:32:42,025] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:62297]
[2022-12-16 20:34:22,483] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:62353]
[2022-12-16 20:34:22,717] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.10, 127.0.0.1:62356]
[2022-12-16 20:34:26,656] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:62364]
[2022-12-16 20:35:24,616] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:62431]
[2022-12-16 20:35:24,677] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.23, 127.0.0.1:62432]
[2022-12-16 20:35:24,786] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.07, 127.0.0.1:62437]
[2022-12-16 20:35:25,126] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.10, 127.0.0.1:62440]
[2022-12-16 20:36:04,830] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:62493]
[2022-12-16 20:36:05,005] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:62496]
[2022-12-16 20:36:05,181] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.06, 127.0.0.1:62500]
[2022-12-16 20:36:05,567] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.13, 127.0.0.1:62503]
[2022-12-16 20:36:40,079] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.19, 127.0.0.1:62551]
[2022-12-16 20:36:40,140] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:62552]
[2022-12-16 20:36:41,104] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.28, 127.0.0.1:62558]
[2022-12-16 20:36:41,297] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.16, 127.0.0.1:62563]
[2022-12-16 20:36:52,411] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.22, 127.0.0.1:62595]
[2022-12-16 20:36:52,475] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:62596]
[2022-12-16 20:36:53,112] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.22, 127.0.0.1:62602]
[2022-12-16 20:36:53,399] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.19, 127.0.0.1:62606]
[2022-12-16 20:36:56,224] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.40, 127.0.0.1:62617]
[2022-12-16 20:36:56,733] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.84, 127.0.0.1:62619]
[2022-12-16 20:36:57,258] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.47, 127.0.0.1:62626]
[2022-12-16 20:36:57,382] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.16, 127.0.0.1:62630]
[2022-12-16 20:37:20,629] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.27, 127.0.0.1:62675]
[2022-12-16 20:37:20,672] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.27, 127.0.0.1:62676]
[2022-12-16 20:37:21,790] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.12, 127.0.0.1:62690]
[2022-12-16 20:37:21,822] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.16, 127.0.0.1:62689]
[2022-12-16 20:37:27,602] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.28, 127.0.0.1:62705]
[2022-12-16 20:37:27,711] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.37, 127.0.0.1:62706]
[2022-12-16 20:37:28,721] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.43, 127.0.0.1:62713]
[2022-12-16 20:37:28,742] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.36, 127.0.0.1:62717]
[2022-12-16 20:39:47,364] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:62900]
[2022-12-16 20:39:47,615] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:62903]
[2022-12-16 20:39:47,929] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.12, 127.0.0.1:62907]
[2022-12-16 20:39:48,317] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.21, 127.0.0.1:62912]
[2022-12-16 20:39:48,432] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:62916]
[2022-12-16 20:39:48,762] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.10, 127.0.0.1:62919]
[2022-12-16 20:39:49,309] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.16, 127.0.0.1:62927]
[2022-12-16 20:39:49,345] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.19, 127.0.0.1:62928]
[2022-12-16 20:40:06,269] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:62959]
[2022-12-16 20:40:06,541] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:62962]
[2022-12-16 20:40:06,726] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.11, 127.0.0.1:62966]
[2022-12-16 20:40:07,048] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.12, 127.0.0.1:62970]
[2022-12-16 20:43:31,512] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.25, 127.0.0.1:63374]
[2022-12-16 20:43:31,581] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.26, 127.0.0.1:63376]
[2022-12-16 20:43:32,336] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.18, 127.0.0.1:63379]
[2022-12-16 20:43:32,663] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.18, 127.0.0.1:63384]
[2022-12-16 20:43:49,309] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.29, 127.0.0.1:63411]
[2022-12-16 20:43:49,552] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.35, 127.0.0.1:63414]
[2022-12-16 20:43:49,849] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.27, 127.0.0.1:63418]
[2022-12-16 20:43:50,139] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.18, 127.0.0.1:63422]
[2022-12-16 20:43:58,229] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:63433]
[2022-12-16 20:44:08,324] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:63447]
[2022-12-16 20:44:08,340] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:63448]
[2022-12-16 20:44:08,556] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.12, 127.0.0.1:63454]
[2022-12-16 20:44:08,856] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.11, 127.0.0.1:63457]
[2022-12-16 20:47:42,612] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:63545]
[2022-12-16 20:47:42,919] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:63548]
[2022-12-16 20:47:42,999] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.07, 127.0.0.1:63552]
[2022-12-16 20:47:43,318] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.08, 127.0.0.1:63555]
[2022-12-16 20:48:05,766] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /cases/32 200 [2.25, 127.0.0.1:63566]
[2022-12-16 20:48:08,904] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:63575]
[2022-12-16 20:48:13,234] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:63584]
[2022-12-16 20:48:13,254] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:63585]
[2022-12-16 20:48:13,358] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/32 200 [0.04, 127.0.0.1:63589]
[2022-12-16 20:48:13,745] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.12, 127.0.0.1:63593]
[2022-12-16 20:48:22,550] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:63599]
[2022-12-16 20:49:33,930] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:63648]
[2022-12-16 20:49:33,984] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:63649]
[2022-12-16 20:49:34,114] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.03, 127.0.0.1:63655]
[2022-12-16 20:49:34,377] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.07, 127.0.0.1:63659]
[2022-12-16 20:58:08,494] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.42, 127.0.0.1:63900]
[2022-12-16 20:58:22,836] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:63913]
[2022-12-16 20:59:21,528] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.31, 127.0.0.1:63939]
[2022-12-16 20:59:26,928] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.40, 127.0.0.1:63948]
[2022-12-16 21:00:35,676] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:63982]
[2022-12-16 21:00:45,665] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:63999]
[2022-12-16 21:01:13,786] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:64013]
[2022-12-16 21:06:39,236] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.04, 127.0.0.1:64498]
[2022-12-16 21:07:03,861] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:64526]
[2022-12-16 21:10:17,012] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.64, 127.0.0.1:64823]
[2022-12-16 21:10:17,612] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.59, 127.0.0.1:64830]
[2022-12-16 21:11:33,202] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.17, 127.0.0.1:64910]
[2022-12-16 21:11:44,121] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.32, 127.0.0.1:64925]
[2022-12-16 21:12:09,791] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:64949]
[2022-12-16 21:12:10,104] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.30, 127.0.0.1:64954]
[2022-12-16 21:12:20,772] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [1.49, 127.0.0.1:64972]
[2022-12-16 21:12:47,722] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:65007]
[2022-12-16 21:13:00,644] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.24, 127.0.0.1:65022]
[2022-12-16 21:13:08,291] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.16, 127.0.0.1:65036]
[2022-12-16 21:13:11,054] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.43, 127.0.0.1:65046]
[2022-12-16 21:13:11,871] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [1.25, 127.0.0.1:65045]
[2022-12-16 21:13:12,227] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [1.06, 127.0.0.1:65050]
[2022-12-16 21:13:12,371] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.67, 127.0.0.1:65054]
[2022-12-16 21:13:12,992] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:65062]
[2022-12-16 21:13:18,197] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:65074]
[2022-12-16 21:13:29,390] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:65090]
[2022-12-16 21:13:32,050] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:65093]
[2022-12-16 21:13:32,419] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:65097]
[2022-12-16 21:13:32,839] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.09, 127.0.0.1:65107]
[2022-12-16 21:13:32,914] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.17, 127.0.0.1:65106]
[2022-12-16 21:13:35,767] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:65116]
[2022-12-16 21:13:42,132] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.20, 127.0.0.1:65128]
[2022-12-16 21:14:32,587] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:65205]
[2022-12-16 21:14:44,027] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.60, 127.0.0.1:65232]
[2022-12-16 21:17:56,024] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.21, 127.0.0.1:49168]
[2022-12-16 21:18:20,402] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:49200]
[2022-12-16 21:18:41,659] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:49229]
[2022-12-16 21:22:37,255] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.38, 127.0.0.1:49486]
[2022-12-16 21:22:38,867] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.22, 127.0.0.1:49490]
[2022-12-16 21:22:39,123] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:49493]
[2022-12-16 21:22:41,464] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:49500]
[2022-12-16 21:23:54,887] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:49535]
[2022-12-16 21:23:55,210] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.12, 127.0.0.1:49539]
[2022-12-16 21:24:00,752] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:49548]
[2022-12-16 21:25:24,071] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:49676]
[2022-12-16 21:25:30,013] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:49685]
[2022-12-16 21:25:35,342] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.33, 127.0.0.1:49692]
[2022-12-16 21:25:44,281] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.17, 127.0.0.1:49702]
[2022-12-16 21:26:12,328] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:49725]
[2022-12-16 21:26:13,530] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:49730]
[2022-12-16 21:26:13,886] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.10, 127.0.0.1:49733]
[2022-12-16 21:26:14,393] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.16, 127.0.0.1:49741]
[2022-12-16 21:26:14,503] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.27, 127.0.0.1:49740]
[2022-12-16 21:26:29,992] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.15, 127.0.0.1:49756]
[2022-12-16 21:39:32,324] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.19, 127.0.0.1:50486]
[2022-12-16 21:41:18,258] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.29, 127.0.0.1:50543]
[2022-12-16 21:41:30,874] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:50553]
[2022-12-16 21:41:32,101] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:50561]
[2022-12-16 21:41:34,236] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.15, 127.0.0.1:50564]
[2022-12-16 21:41:36,517] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:50571]
[2022-12-16 21:41:39,562] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:50577]
[2022-12-16 21:41:39,903] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.13, 127.0.0.1:50580]
[2022-12-16 21:41:44,540] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.18, 127.0.0.1:50585]
[2022-12-16 21:41:49,029] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:50595]
[2022-12-16 21:41:49,135] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:50596]
[2022-12-16 21:41:49,418] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/31 200 [0.24, 127.0.0.1:50601]
[2022-12-16 21:41:49,636] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?project= 200 [0.16, 127.0.0.1:50604]
[2022-12-16 21:41:55,370] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.27, 127.0.0.1:50612]
[2022-12-16 21:43:02,652] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.51, 127.0.0.1:50655]
[2022-12-16 21:44:03,931] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:50698]
[2022-12-16 21:44:22,732] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/35 200 [3.11, 127.0.0.1:50722]
[2022-12-16 21:44:22,788] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/34 200 [3.17, 127.0.0.1:50724]
[2022-12-16 21:44:23,544] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/33 200 [3.92, 127.0.0.1:50723]
[2022-12-16 21:44:23,825] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/32 200 [4.24, 127.0.0.1:50718]
[2022-12-16 21:44:23,872] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /cases/31 200 [4.28, 127.0.0.1:50716]
[2022-12-16 21:44:53,202] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.25, 127.0.0.1:50749]
[2022-12-16 21:44:55,059] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.25, 127.0.0.1:50752]
[2022-12-16 21:45:00,172] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.26, 127.0.0.1:50763]
[2022-12-16 21:45:00,191] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.28, 127.0.0.1:50764]
[2022-12-16 21:45:05,428] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:50768]
[2022-12-16 21:45:19,010] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.11, 127.0.0.1:50796]
[2022-12-16 21:46:14,357] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [8.32, 127.0.0.1:50862]
[2022-12-16 21:46:17,237] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css 200 [2.83, 127.0.0.1:50862]
[2022-12-16 21:46:17,325] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap-tweaks.css 200 [2.41, 127.0.0.1:50881]
[2022-12-16 21:46:17,362] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/prettify.css 200 [2.42, 127.0.0.1:50882]
[2022-12-16 21:46:17,407] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/default.css 200 [0.96, 127.0.0.1:50887]
[2022-12-16 21:46:17,587] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/jquery-3.5.1.min.js 200 [1.14, 127.0.0.1:50888]
[2022-12-16 21:46:17,688] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/ajax-form.js 200 [1.24, 127.0.0.1:50889]
[2022-12-16 21:46:17,842] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/csrf.js 200 [0.58, 127.0.0.1:50862]
[2022-12-16 21:46:18,209] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/bootstrap.min.js 200 [0.88, 127.0.0.1:50881]
[2022-12-16 21:46:18,706] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/prettify-min.js 200 [1.32, 127.0.0.1:50882]
[2022-12-16 21:46:19,032] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/default.js 200 [1.61, 127.0.0.1:50887]
[2022-12-16 21:46:20,706] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 200 [3.11, 127.0.0.1:50888]
[2022-12-16 21:46:21,571] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/img/grid.png 200 [3.45, 127.0.0.1:50889]
[2022-12-16 21:46:23,960] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-16 21:46:24,026] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [3.39, 127.0.0.1:50881]
[2022-12-16 21:46:24,954] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-12-16 21:46:25,032] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /favicon.ico 404 [0.99, 127.0.0.1:50881]
[2022-12-16 21:48:06,884] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:50976]
[2022-12-16 21:48:06,885] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.14, 127.0.0.1:50977]
